name: Deploy Finance Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Step 3: Install dependencies and build frontend
      - name: Install dependencies and build frontend
        working-directory: ./frontend
        run: |
          rm -rf node_modules package-lock.json
          npm install --legacy-peer-deps
          npm run build

      # Step 4: Install dependencies for backend
      - name: Install dependencies for backend
        working-directory: ./backend
        run: npm ci

      # Step 5: Start Backend with PM2
      - name: Restart Backend with PM2
        working-directory: ./backend
        run: |
          touch .env
          echo "${{secrets.FINANCEENV}}" > .env
          pm2 restart Backend || pm2 start "npm run start" --name Backend

      # Step 6: Start or Reload Frontend with PM2
      - name: Start or Reload Frontend with PM2
        working-directory: ./frontend
        run: |
          echo "${{secrets.FINANCE_UI}}" > .env
          if pm2 describe Frontend > /dev/null; then
            pm2 reload Frontend --update-env
          else
            pm2 start "serve -s dist --listen 5173" --name Frontend --update-env
          fi

      # Step 7: Save PM2 process list
      - name: Save PM2 process list
        run: pm2 save
