name: Node.js CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4 # Step 1: Checkout the code

      - name: Use Node.js ${{ matrix.node-version }} # Step 2: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Verify directory structure
        run: ls -R # Verify the repo structure to ensure we're working in the correct path

      - name: Install dependencies in app directory # Step 3: Install dependencies
        run: npm ci # This runs the npm command
        working-directory: ${{ github.workspace }}/backend # Ensure this points to the correct directory
